# Generated by Django 3.2.4 on 2022-09-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(upload_to='Course/')),
                ('description', models.TextField(max_length=5000)),
                ('language', models.CharField(max_length=1000, null=True)),
                ('speaker', models.CharField(max_length=1000, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('video', models.CharField(default='', max_length=200, null=True)),
                ('time_zone', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=3000, null=True)),
                ('comment', models.TextField(max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to_director', models.BooleanField(default=False)),
                ('is_accept', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('user_add', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(upload_to='Seminar/')),
                ('description', models.TextField(max_length=5000)),
                ('language', models.CharField(max_length=1000, null=True)),
                ('speaker', models.CharField(max_length=1000, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('video', models.CharField(default='', max_length=200, null=True)),
                ('time_zone', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('user_add', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_event.mainfield')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('unique_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=1000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(null=True)),
                ('duration', models.CharField(default=0, max_length=50)),
                ('status', models.CharField(choices=[('Create', 'Create'), ('Reject', 'Reject'), ('Revise', 'Revise'), ('Remove', 'Remove'), ('Select_expert', 'Select_expert'), ('Expert_decide', 'expert_decide'), ('Resubmit_to_expert', 'Resubmit_to_expert'), ('Resubmit_to_director', 'Resubmit_to_director'), ('Published', 'Published')], default='Select_expert', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contract', models.FileField(null=True, upload_to='')),
                ('sign', models.TextField(max_length=50000, null=True)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_field', models.ManyToManyField(to='virtual_event.MainField')),
                ('sub_field', models.ManyToManyField(to='virtual_event.SubField')),
                ('top_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(upload_to='workshop/')),
                ('description', models.TextField(max_length=5000)),
                ('language', models.CharField(max_length=1000, null=True)),
                ('speaker', models.CharField(max_length=1000, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('video', models.CharField(default='', max_length=200, null=True)),
                ('time_zone', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualEventTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('expert', 'expert'), ('director', 'director'), ('presenter', 'presenter')], default='supervisor', max_length=50)),
                ('status', models.CharField(default='create_workshop', max_length=100, null=True)),
                ('desc', models.TextField(choices=[('Virtual event created by presenter and pending for process.', 'Create'), ('Virtual event rejected.', 'Reject'), ('Virtual event revise ,pending presenter decision.', 'Revise'), ('Virtual event removed by presenter', 'Remove'), ('pending for director select expert.', 'Select Expert'), ('Director selected expert and pending for expert decide.', 'Expert Decide'), ('The virtual event resubmit to expert.', 'Resubmit To Expert'), ('The virtual event resubmit to director.', 'Resubmit To Director'), ('virtual event published in site.', 'Published')], default='Virtual event created by presenter and pending for process.', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('vitual_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_event.virtualevent')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualEventMemebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(blank=True, default='All', max_length=50)),
                ('certificate', models.FileField(blank=True, default=None, null=True, upload_to='virtualevent/certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('virtual_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_event.virtualevent')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.CharField(max_length=50, null=True)),
                ('end_time', models.CharField(max_length=50, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('video_link', models.CharField(max_length=200, null=True)),
                ('document', models.FileField(max_length=500, null=True, upload_to='virtualevent/')),
                ('vitual_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_event.virtualevent')),
            ],
        ),
        migrations.CreateModel(
            name='EditTimetableRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('editrequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_event.editrequest')),
                ('time_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_event.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='editrequest',
            name='virtual_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_event.virtualevent'),
        ),
    ]
