# Generated by Django 3.2.4 on 2022-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
