# Generated by Django 3.2.4 on 2021-10-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivc_website', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Course', max_length=100, unique=True)),
                ('from_time', django_jalali.db.models.jDateTimeField(verbose_name='From')),
                ('to_time', django_jalali.db.models.jDateTimeField(verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborateStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_region', models.CharField(max_length=5, null=True)),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Phone number')),
                ('cv', models.FileField(help_text='Should be in PDF format', upload_to='collaborate_staff/', verbose_name='CV')),
                ('about', models.TextField(verbose_name="Why do you think you're eligible for this?")),
                ('time_spend', models.PositiveIntegerField(verbose_name='The amount of hour you can spend per day')),
                ('is_member', models.BooleanField(verbose_name='Are you a company member?')),
                ('without_project', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('recommendation', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborateStaffProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc_website.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborate_with_us.collaboratestaff')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborateStaffInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=150)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborate_with_us.collaboratestaff')),
            ],
        ),
    ]
