# Generated by Django 4.0.4 on 2022-06-07 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('field_of_study', models.CharField(choices=[('Biomedical Engineering', 'Biomedical Engineering'), ('Biotechnology', 'Biotechnology'), ('Business', 'Business'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Data Science', 'Data Science'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Environmental Engineering', 'Environmental Engineering'), ('Industrial Engineering', 'Industrial Engineering'), ('Material Science', 'Material Science'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Medical Informatics', 'Medical Informatics'), ('Medical Physics', 'Medical Physics'), ('Medicine', 'Medicine'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Nuclear Medicine Physician', 'Nuclear Medicine Physician'), ('Nuclear physics', 'Nuclear physics'), ('Physics', 'Physics'), ('Statistics', 'Statistics'), ('Medical Engineering', 'Medical Engineering'), ('Other', 'Other')], default='', max_length=155, verbose_name='Field Of Study')),
                ('degree', models.CharField(choices=[('Diploma', 'Diploma'), ("Bachelor's degree", "Bachelor's degree"), ("Master's degree", "Master's degree"), ('Doctoral degree', 'Doctoral degree')], default='', max_length=50, verbose_name='Degree')),
                ('phone', models.CharField(max_length=17, null=True, verbose_name='Phone')),
                ('phone_region', models.CharField(default='IR', max_length=5)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Employee', 'Employee'), ('Company Manager', 'Company Manager'), ('Post-Doctoral', 'Post-Doctoral'), ('Other', 'Other')], default='', max_length=50, null=True, verbose_name='Status')),
                ('cv_file', models.FileField(help_text='It should be in PDF format', upload_to='applicants/pdf', verbose_name='CV File')),
                ('is_valid', models.BooleanField(default=False)),
                ('applicant_token', models.CharField(default='', max_length=20)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('referred_by', models.CharField(choices=[('Friends', 'Friends'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Telegram', 'Telegram'), ('Linkedin', 'Linkedin'), ('Search Engine', 'Search Engine')], default='', max_length=200, null=True, verbose_name='Referred by')),
                ('is_internship', models.BooleanField(default=False, null=True, verbose_name='Internship')),
            ],
        ),
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_field', models.CharField(max_length=200)),
                ('suggested_by', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LegalApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Agent First Name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Agent Last Name')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, null=True, verbose_name='Phone')),
                ('phone_region', models.CharField(default='IR', max_length=5)),
                ('is_valid', models.BooleanField(default=False)),
                ('applicant_token', models.CharField(default='', max_length=20)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
