# Generated by Django 3.2.4 on 2022-07-24 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20220716_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryformclient',
            name='question_w6',
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 6, 29, 19, 288237, tzinfo=utc), null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='id_project',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 6, 29, 19, 288190, tzinfo=utc), null=True, verbose_name='Strat Date'),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 6, 29, 19, 334884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='time_meeting',
            field=models.TimeField(default=datetime.datetime(2022, 7, 24, 6, 29, 19, 334981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 6, 29, 19, 312561, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 6, 29, 19, 312518, tzinfo=utc), null=True),
        ),
    ]
