# Generated by Django 3.2.4 on 2022-07-24 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20220724_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryformclient',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 8, 51, 6, 567317, tzinfo=utc), null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 8, 51, 6, 567251, tzinfo=utc), null=True, verbose_name='Strat Date'),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 8, 51, 6, 587873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='time_meeting',
            field=models.TimeField(default=datetime.datetime(2022, 7, 24, 8, 51, 6, 587915, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 8, 51, 6, 578001, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 8, 51, 6, 577963, tzinfo=utc), null=True),
        ),
    ]
