# Generated by Django 3.2.4 on 2022-07-27 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20220724_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmeeting',
            name='time_zone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 6, 27, 40, 635278, tzinfo=utc), null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 6, 27, 40, 635278, tzinfo=utc), null=True, verbose_name='Strat Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='status',
            field=models.CharField(choices=[('n', 'is_new'), ('e', 'is_expert'), ('s', 'is_supervisor'), ('not-pay', 'Not pay'), ('r', 'Rejected by director'), ('rejected_by_expert', 'Rejected by expert'), ('m', 'is_main_supervisor'), ('withdrew', 'withdrew'), ('send-contract-to-client', 'send-contract-to-client'), ('send-signed-contract', 'send-signed-contract'), ('revised-contract', 'revised-contract'), ('send-contract-to-director', 'send-contract-to-director'), ('revise-contract-by-director', 'revise-contract-to-director'), ('accept-contract-by-director', 'accept-contract-by-director'), ('not-response-contract', 'not-response-contract'), ('d', 'delete_project'), ('created', 'created'), ('hidden', 'hidden'), ('expert_reviewer', 'Expert reviewer'), ('expert_send_scores_to_director', 'expert_send_scores_to_director'), ('revise_director_to_client', 'revise_director_to_client')], default='n', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industryformexpert',
            name='status',
            field=models.CharField(choices=[('m', 'main__supervisor'), ('n', 'new'), ('s', 'supervisor'), ('v', 'view_main__supervisor'), ('h', 'hidden'), ('view_projects', 'view_projects'), ('review', 'Review'), ('review_project', 'Review project'), ('expert_send_scores_to_director', 'expert_send_scores_to_director'), ('revise_director_to_expert', 'revise_director_to_expert'), ('revise_director_to_client', 'revise_director_to_client'), ('send-contract-to-client', 'send-contract-to-client'), ('send-signed-contract', 'send-signed-contract'), ('revised-contract', 'revised-contract'), ('send-contract-to-director', 'send-contract-to-director'), ('revise-contract-to-director', 'revise-contract-to-director'), ('accept-contract-by-director', 'accept-contract-by-director'), ('not-response-contract', 'not-response-contract'), ('reviewer_project', 'Reviewer project'), ('chek_score', 'Chek score'), ('is_change', 'is_change')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industryreviewer',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('r', 'reject'), ('a', 'accept'), ('e', 'expert'), ('s', 'not_see'), ('breach_of_promis_p', 'Breach of promise proposal'), ('cancel_by_expert', 'Cancel by expert'), ('cancel_by_expert_p', 'Cancel by expert project'), ('automatically_cancel', 'Automatically Revise proposal'), ('automatically_cancel_p', 'Automatically Revise project'), ('revise_by_expert', 'Revise by expert'), ('revise_by_expert_p', 'Revise by expert project'), ('new_project', 'New project'), ('reject_project', 'Reject project'), ('accept_project', 'Accept project'), ('send_director_project', 'Send to director project'), ('not_see_project', 'Not see project'), ('breach_of_promis', 'Breach of promise')], default='n', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 6, 27, 40, 640265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='time_meeting',
            field=models.TimeField(default=datetime.datetime(2022, 7, 27, 6, 27, 40, 640265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 6, 27, 40, 637273, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 6, 27, 40, 637273, tzinfo=utc), null=True),
        ),
    ]
