# Generated by Django 3.2.4 on 2022-08-09 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20220727_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='proposal_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_foreignkey', to='research.industryformexpert'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 33, 47, 994041, tzinfo=utc), null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='follow_project',
            field=models.CharField(choices=[('new', 'New'), ('send_review', 'Send review'), ('check_score', 'Check score'), ('change_to_new_status', 'Change to new status'), ('p_main_new', 'new main supervisor'), ('p_main_send_review', 'new main supervisor'), ('p_main_send_proposal_director', 'p_main_send_proposal_director'), ('p_main_revise_project_director', 'p_main_revise_project_director'), ('p_main_revise_proposal_by_expert', 'p_main_revise_proposal_by_expert'), ('p_main_revise_proposal_by_director', 'p_main_revise_proposal_by_director'), ('p_main_not_response_revised_proposal', 'p_main_not_response_revised_proposal'), ('p_main_not_response_revised_proposal_send_to_director', 'p_main_not_response_revised_proposal_send_to_director'), ('p_main_resubmition_proposal', 'p_main_resubmition_proposal'), ('p_main_accept_proposal_director', 'p_main_accept_proposal_director'), ('p_main_contract_sent_supervisor', 'p_main_contract_sent_supervisor'), ('p_main_contract_sent_to_expert', 'p_main_contract_sent_to_expert'), ('p_main_contract_revise', 'p_main_contract_revise'), ('p_main_contract_revise_by_director', 'p_main_contract_revise_by_director'), ('p_main_change_to_new_to_status', 'p_main_change_to_new_to_status'), ('under-process-by-expert', 'under-process-by-expert'), ('send_contract_to_client', 'send_contract_to_client'), ('sent_contract_to_client', 'sent_contract_to_client'), ('send_signed_contract', 'send_signed_contract'), ('revised_contract', 'revised_contract'), ('under_process_by_expert', 'Under process by expert')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 33, 47, 994041, tzinfo=utc), null=True, verbose_name='Strat Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='status',
            field=models.CharField(choices=[('n', 'is_new'), ('e', 'is_expert'), ('s', 'is_supervisor'), ('not-pay', 'Not pay'), ('r', 'Rejected by director'), ('rejected_by_expert', 'Rejected by expert'), ('m', 'is_main_supervisor'), ('withdrew', 'withdrew'), ('send-contract-to-client', 'send-contract-to-client'), ('send-signed-contract', 'send-signed-contract'), ('revised-contract', 'revised-contract'), ('send-contract-to-director', 'send-contract-to-director'), ('revise-contract-by-director', 'revise-contract-to-director'), ('accept-contract-by-director', 'accept-contract-by-director'), ('not-response-contract', 'not-response-contract'), ('d', 'delete_project'), ('created', 'created'), ('hidden', 'hidden'), ('expert_reviewer', 'Expert reviewer'), ('expert_send_scores_to_director', 'expert_send_scores_to_director'), ('revise_director_to_expert', 'revise_director_to_expert'), ('revise_director_to_client', 'revise_director_to_client'), ('resubmited_project', 'resubmited_project'), ('accept_project_pending_send_contarct_client', 'accept_project_pending_send_contarct_client'), ('resubmited_project_send_to_director', 'resubmited_project_send_to_director')], default='n', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='industryformexpert',
            name='status',
            field=models.CharField(choices=[('m', 'main__supervisor'), ('n', 'new'), ('s', 'supervisor'), ('v', 'view_main__supervisor'), ('h', 'hidden'), ('view_projects', 'view_projects'), ('review', 'Review'), ('review_project', 'Review project'), ('expert_send_scores_to_director', 'expert_send_scores_to_director'), ('revise_director_to_expert', 'revise_director_to_expert'), ('revise_director_to_client', 'revise_director_to_client'), ('resubmited_project', 'resubmited_project'), ('resubmited_project_send_to_director', 'resubmited_project_send_to_director'), ('accept_project_pending_send_contarct_client', 'accept_project_pending_send_contarct_client'), ('send-contract-to-client', 'send-contract-to-client'), ('send-signed-contract', 'send-signed-contract'), ('revised-contract', 'revised-contract'), ('send-contract-to-director', 'send-contract-to-director'), ('revise-contract-to-director', 'revise-contract-to-director'), ('accept-contract-by-director', 'accept-contract-by-director'), ('not-response-contract', 'not-response-contract'), ('reviewer_project', 'Reviewer project'), ('chek_score', 'Chek score'), ('is_change', 'is_change')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 33, 48, 1017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='time_meeting',
            field=models.TimeField(default=datetime.datetime(2022, 8, 9, 8, 33, 48, 1017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 33, 47, 998032, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 33, 47, 998032, tzinfo=utc), null=True),
        ),
    ]
