# Generated by Django 3.2.4 on 2022-08-09 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20220809_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryformclient',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 38, 13, 69917, tzinfo=utc), null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 38, 13, 69917, tzinfo=utc), null=True, verbose_name='Strat Date'),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 38, 13, 76869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='time_meeting',
            field=models.TimeField(default=datetime.datetime(2022, 8, 9, 8, 38, 13, 76869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('on_going', 'On going'), ('pending', 'Pending'), ('on_hold', 'On hold'), ('done', 'Done'), ('delete', 'Delete'), ('send_proposal', 'Send proposal'), ('deadline_is_over', 'The deadline is over')], default='new', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 38, 13, 73906, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 8, 38, 13, 73906, tzinfo=utc), null=True),
        ),
    ]
