# Generated by Django 3.2.4 on 2022-08-11 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_auto_20220811_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='not_supervisor',
        ),
        migrations.AddField(
            model_name='requestuserforproject',
            name='expert_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_requests', to='research.industryformexpert'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 11, 4, 55, 451397, tzinfo=utc), null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='industryformclient',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 11, 4, 55, 451349, tzinfo=utc), null=True, verbose_name='Strat Date'),
        ),
        migrations.AlterField(
            model_name='requestuserforproject',
            name='status',
            field=models.CharField(choices=[('not-pay', 'not-pay'), ('accept', 'Accept'), ('reject', 'Reject'), ('remove', 'Remove'), ('rejection-contract', 'rejection-contract'), ('request', 'Request'), ('delete', 'Deleted')], default='request', max_length=50, verbose_name='Choose your position!'),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 11, 4, 55, 471532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchmeeting',
            name='time_meeting',
            field=models.TimeField(default=datetime.datetime(2022, 8, 11, 11, 4, 55, 471580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('on_going', 'On going'), ('pending', 'Pending'), ('on_hold', 'On hold'), ('done', 'Done'), ('delete', 'Delete'), ('under_process_supervisor', 'under_process_supervisor'), ('send_proposal', 'Send proposal'), ('deadline_is_over', 'The deadline is over')], default='new', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 11, 4, 55, 460817, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeprogramming',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 11, 4, 55, 460772, tzinfo=utc), null=True),
        ),
    ]
