# Generated by Django 3.2.4 on 2022-07-15 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pay', models.CharField(max_length=100, null=True, unique=True)),
                ('paymented', models.IntegerField(default=0, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('amount', models.FloatField(null=True)),
                ('pymeny_method', models.CharField(max_length=100, null=True)),
                ('gsp', models.FloatField(null=True)),
                ('pst', models.FloatField(null=True)),
                ('additional_fee', models.FloatField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('zarinpal_amount', models.IntegerField(null=True)),
                ('success_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('back_url', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchased_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('payment_intent', models.CharField(max_length=100, null=True)),
                ('has_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Automatically', models.BooleanField(default=True, null=True)),
                ('price', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
