# Generated by Django 3.2.4 on 2022-08-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_rename_whitdrawalbox_request_money_witdrawalbox'),
        ('payment_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice'),
        ),
    ]
