# Generated by Django 3.2.4 on 2021-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalopinion',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
