# Generated by Django 3.2.4 on 2021-10-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_proposalopinion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalopinion',
            name='description',
        ),
    ]
