"""
Django settings for ivc_project project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^gt#fqucjf-%%nhq_@m$_uv2)!i4!5v$h!q)vm1e9nzmd*n$^#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ADMINS = [('ceo', 'm.salmanpoor66@gmail.com'), ('cto', 'hossin_sheykhi@yahoo.com')]

ALLOWED_HOSTS = ['4d4e-45-61-49-186.ngrok.io', '127.0.0.1','Tecvico.com','www.tecvico.com','172.105.86.212','139.162.144.195','Tecvico.ca','Tecvico.org','Tecvico.ir','Tecvico.org','Tecvico.net','www.Tecvico.ca','www.Tecvico.org','www.Tecvico.ir','www.Tecvico.org','www.Tecvico.net']

# Application definition

INSTALLED_APPS = [
    # 'azbankgateways',
    'gtm',
    'workshop',
    'clearcache',
    'multiselectfield',
    'crispy_forms',
    'ckeditor',
    'django_jalali',
    'task_tracker',
    'cartable',
    'payment_stripe.apps.PaymentStripeConfig',
    'seo.apps.SeoConfig',
    'log.apps.LogConfig',
    'blog.apps.BlogConfig',
    'FAQ.apps.FaqConfig',
    'coin.apps.CoinConfig',
    'Q_And_A.apps.QAndAConfig',
    'competition.apps.CompetitionConfig',
    'collaborate_with_us.apps.CollaborateWithUsConfig',
    'industrial_manager.apps.IndustrialManagerConfig',
    'ivc_website.apps.IvcWebsiteConfig',
    'dashboard.apps.DashboardConfig',
    'courses.apps.CoursesConfig',
    'users.apps.UsersConfig',
    'join.apps.JoinConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # to get human time (like 5 minutes ago) for notifications
    'django.contrib.sites',  # add sites to installed apps
    'django.contrib.sitemaps',  # add Django sitemaps to installed apps
    'forum.apps.ForumConfig',
    'comment',
    'paypal.standard.ipn',
    'research.apps.ResearchConfig',
    'email_app.apps.EmailAppConfig',
    'request.apps.RequestConfig',
    'zarinpal.apps.ZarinpalConfig',
    'accounting',
    'chartjs'

]

SITE_ID = 1  # define the site id

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # FOR PERSIAN LANGUAGE
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'ivc_project.middleware.AutoLogout'
]

ROOT_URLCONF = 'ivc_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.views.notification',
                'ivc_website.views.translate_ir',
                'ivc_website.views.check_visitor'
            ],
        },
    },
]

WSGI_APPLICATION = 'ivc_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
'default': {
    'ENGINE': 'django.db.backends.mysql', 
    'NAME': 'tecvicoc_db',
    'USER': 'tecvicoc_admin',
    'PASSWORD': 'gHgDHSXp^3PZ',
    'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
    'PORT': '3306',
    'OPTIONS': {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        'charset': 'utf8mb4',
    }
} }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, "mydatabase"),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'fa'  # FOR PERSIAN LANGUAGE

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
IVC_WEBSITE_ROOT = os.path.join(BASE_DIR, 'ivc_website')
INDUSTRIAL_EMAIL_DATA_DIR = os.path.join(BASE_DIR, 'industrial_manager/data')

MEDIA_ROOT = os.path.join('/home/tecvicoc/public_html', 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'dashboard-page'
LOGIN_URL = 'login'

# for password-reset:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST = 'mail.tecvico.com'
#EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'tecvico2020@gmail.com'
#EMAIL_HOST_PASSWORD = 'soroCoopEr@7823984'
#EMAIL_HOST_USER = 'dr.mghaemi@gmail.com'
#EMAIL_HOST_PASSWORD = 'Mmgh100122'
EMAIL_HOST_USER = 'info@tecvico.com'
EMAIL_HOST_PASSWORD = '@!tecvico2020#'
DEFAULTE_HOST_USER = EMAIL_HOST_USER


AUTHENTICATION_BACKENDS = ['users.custom_login.EmailBackend']  # to use email address instead of username on login page

# for session timeout:
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_AGE = 15 * 60  # logout after 15 minutes

GOOGLE_RECAPTCHA_SECRET_KEY = '6LfNkwsaAAAAAL0kkq8wPIHjiiaIetAIGlcTzz9b'

LOCALE_PATHS = [  # FOR PERSIAN LANGUAGE
    os.path.join(BASE_DIR, 'locale')
]

GOOGLE_TAG_ID = 'GTM-WW86MC6'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

#STRIPE_PRIVATE_KEY = "sk_test_51JSP4oHqDsGa1SRrAPrTxZUwXD2v9pSw3c39gLwjm6Gx8sUpfgCCYCPCVGCUxz73aaAJfcxAsdjtMgrmKr87C5lr00qFXK7pne"
STRIPE_PRIVATE_KEY = "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"

TEMPLATED_EMAIL_BACKEND  =  'templated_email.backends.vanilla_django.TemplateBackend'
PAYPAL_RECEIVER_EMAIL = 'info@tecvico.com'
PAYPAL_TEST = False

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
