# Generated by Django 3.2.4 on 2021-09-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_auto_20210916_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktracker',
            name='task_percent',
        ),
    ]
