# Generated by Django 3.2.4 on 2022-07-15 19:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainfield', to='workshop.mainfield')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=30)),
                ('capacity', models.IntegerField(default=0, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1000)),
                ('time_to_start', models.TimeField(default=datetime.datetime(2022, 7, 15, 19, 27, 7, 288311, tzinfo=utc))),
                ('date', models.DateField(default=datetime.datetime(2022, 7, 15, 19, 27, 7, 288311, tzinfo=utc))),
                ('price', models.IntegerField()),
                ('duration', models.CharField(default=0, max_length=50)),
                ('image', models.ImageField(upload_to='workshop/')),
                ('load_pdf', models.FileField(default='', max_length=500, upload_to='workshop/')),
                ('description', models.TextField(max_length=5000)),
                ('address', models.TextField(max_length=1000)),
                ('prev_experience', models.TextField(max_length=2500)),
                ('work_with_us', models.IntegerField(default=0, null=True)),
                ('work_with_others', models.IntegerField(default=0, null=True)),
                ('proof_file', models.FileField(default='', null=True, upload_to='workshop/')),
                ('language', models.CharField(max_length=1000, null=True)),
                ('speaker', models.CharField(max_length=1000, null=True)),
                ('suggest_country', models.CharField(max_length=1000, null=True)),
                ('keyword', models.CharField(max_length=1000, null=True)),
                ('skills', models.CharField(max_length=1000, null=True)),
                ('video', models.CharField(default='', max_length=200, null=True)),
                ('status', models.CharField(default='Set_time_table', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time_zone', models.CharField(default='', max_length=1000, null=True)),
                ('add_field', models.CharField(default='', max_length=1000, null=True)),
                ('guaranteed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.guarante')),
                ('main_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop', to='workshop.mainfield')),
                ('sub_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop', to='workshop.subfield')),
                ('top_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dawdn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('expert', 'expert'), ('director', 'director'), ('supervisor', 'supervisor')], default='supervisor', max_length=50)),
                ('status', models.CharField(default='create_workshop', max_length=100, null=True)),
                ('desc', models.TextField(choices=[('workshop created by supervisor and pending for pay guarante', 'Pay Guarante'), ('Create invoice by supervisor but not paid yet', 'Notpay'), ('supervisor pay invoice and workshop send to director for select expert', 'Guarante Accept'), ('workshop send to expert by director', 'Expert Decide'), ('workshop decline by expert', 'Reject Expert'), ('Expert accept evaluate workshop', 'Expert Comment'), ('Expert evaluated workshop', 'Manager Check'), ('supervisor edit workshop', 'Manager Check From Supervisor'), ('Workshop accepted by director', 'Accept'), ('Workshop revise by director', 'Revise To Expert'), ('Workshop reject by director', 'Reject'), ('Director approved the workshop and now expert has to sending the contract for supervisor', 'Approve Contract'), ('Expert upload contract and send to supervisor for assign', 'Upload Contract'), ('Supervisor send contract to expert', 'Send Contract By Supervisor'), ('Expert wants the revising the contract and to send contract to supervisor', 'Revise Contract To Supervisor'), ('Expert sent contract to director', 'Send Contract To Director'), ('Contract revise by director and send to expert', 'Revise Contract To Expert'), ('Director rejected contract', 'Reject Contract To Supervisor'), ('Contract send to supervisor', 'Send Contract To Supervisor')], default='workshop created by supervisor and pending for pay guarante', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to_do', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=False)),
                ('step', models.IntegerField(default=1)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Users_Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(blank=True, default='All', max_length=50)),
                ('certificate', models.FileField(default=None, null=True, upload_to='workshop/certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.CharField(max_length=50, null=True)),
                ('end_time', models.CharField(max_length=50, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('video_link', models.CharField(max_length=200, null=True)),
                ('information', models.FileField(null=True, upload_to='workshop/time_table/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.TextField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dawdnbge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default='ltr', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('coursetitles_title', models.CharField(max_length=50)),
                ('coursetitles', models.TextField(max_length=5000)),
                ('courseclients_title', models.CharField(max_length=50)),
                ('courseclients', models.TextField(max_length=5000)),
                ('certificate_title', models.CharField(max_length=50)),
                ('certificatedesc', models.TextField(max_length=5000)),
                ('content', models.TextField(max_length=20000)),
                ('coursespeakers_title', models.CharField(max_length=50)),
                ('coursespeakers', models.TextField(max_length=10000)),
                ('registeration_title', models.CharField(max_length=50)),
                ('registeration_content', models.TextField(max_length=20000)),
                ('logo_image', models.ImageField(blank=True, upload_to='workshop/')),
                ('banner_image', models.ImageField(upload_to='workshop/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('is_checked', models.BooleanField(default=False, null=True)),
                ('expert_price', models.IntegerField(default=0, null=True)),
                ('access', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Approve', 'Approve'), ('Decline', 'Decline')], default='New', max_length=30)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dawdnad', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_comment', to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Adverstiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=5000)),
                ('coursetitles', models.TextField(max_length=5000)),
                ('courseclients', models.TextField(max_length=5000)),
                ('certificatedesc', models.TextField(max_length=5000)),
                ('content', models.TextField(max_length=5000)),
                ('coursespeakers', models.TextField(max_length=5000)),
                ('logo_image', models.ImageField(upload_to='workshop/')),
                ('contracts', models.FileField(upload_to='workshop/contracts/')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False)),
                ('comment', models.TextField(max_length=200, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('approve_contract', models.BooleanField(default=False, null=True)),
                ('contract', models.FileField(default=None, null=True, upload_to='workshop/contracts/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accept_reject', to='workshop.workshop')),
            ],
        ),
    ]
