# Generated by Django 3.2.4 on 2022-07-21 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 6, 54, 9, 38870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time_to_start',
            field=models.TimeField(default=datetime.datetime(2022, 7, 21, 6, 54, 9, 38870, tzinfo=utc)),
        ),
    ]
