# Generated by Django 3.2.4 on 2022-07-24 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20220721_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 7, 24, 56, 643401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time_to_start',
            field=models.TimeField(default=datetime.datetime(2022, 7, 24, 7, 24, 56, 643401, tzinfo=utc)),
        ),
    ]
