# Generated by Django 3.2.4 on 2022-07-30 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20220724_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='expert_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 30, 7, 54, 16, 891895, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time_to_start',
            field=models.TimeField(default=datetime.datetime(2022, 7, 30, 7, 54, 16, 891895, tzinfo=utc)),
        ),
    ]
