# Generated by Django 3.2.4 on 2022-07-30 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20220730_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 30, 12, 6, 21, 168987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time_to_start',
            field=models.TimeField(default=datetime.datetime(2022, 7, 30, 12, 6, 21, 168936, tzinfo=utc)),
        ),
    ]
