# Generated by Django 3.2.4 on 2022-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_userfootprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfootprint',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
