# Generated by Django 3.2.4 on 2022-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_userfootprint_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfootprint',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
