# Generated by Django 3.2.4 on 2022-08-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_alter_userfootprint_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfootprint',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
