# Generated by Django 3.2.4 on 2022-09-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
        ('request', '0001_initial'),
        ('research', '0001_initial'),
        ('virtual_event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=300)),
                ('location', models.TextField(max_length=300)),
                ('country', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('input', models.IntegerField(default=0, null=True)),
                ('output', models.IntegerField(default=0, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('membership_code', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('real', 'real'), ('percent', 'percent')], default='real', max_length=10)),
                ('is_all', models.BooleanField(default=True)),
                ('usabel_number_all', models.IntegerField(blank=True, default=1)),
                ('is_workshop', models.BooleanField(default=False)),
                ('workshop_amount', models.IntegerField(blank=True, default=0)),
                ('usabel_number_workshop', models.IntegerField(blank=True, default=0)),
                ('is_project', models.BooleanField(default=False)),
                ('project_amount', models.IntegerField(blank=True, default=0)),
                ('usabel_number_project', models.IntegerField(blank=True, default=0)),
                ('is_badge_request', models.BooleanField(default=False)),
                ('badge_request_amount', models.IntegerField(blank=True, default=0)),
                ('usabel_number_badge_rquest', models.IntegerField(blank=True, default=0)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('icon', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('UN', 'unknow'), ('V', 'virtual-event'), ('P', 'project'), ('W', 'workshop'), ('BR', 'badgerequest'), ('SR', 'supervisorrequest'), ('WR', 'workshoprequest')], default='UN', max_length=100)),
                ('balance_value', models.IntegerField()),
                ('action', models.CharField(max_length=200, null=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.badgerequest')),
                ('badgesupervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.supervisorrequest')),
                ('badgeworkshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.workshoprequest')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.industryformclient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('virtual_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtual_event.virtualevent')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('requested', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_bank_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('shaba_acoount', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=0)),
                ('position', models.CharField(default='expert', max_length=30, null=True)),
                ('expert_approve', models.BooleanField(default=False, null=True)),
                ('manager_approve', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(default='expert_decide', max_length=50, null=True)),
                ('bank_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.user_bank_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('witdrawalbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.withdrawalbox')),
            ],
        ),
        migrations.CreateModel(
            name='membership_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_pay', models.BooleanField(default=False)),
                ('project_count', models.IntegerField(default=0)),
                ('workshop_count', models.IntegerField(default=0)),
                ('badge_request_count', models.IntegerField(default=0)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
                ('fallow_code', models.CharField(max_length=100)),
                ('session_discount', models.CharField(blank=True, default='0-0', max_length=30, null=True)),
                ('session_membership', models.CharField(blank=True, default='0-0', max_length=30, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('use_status', models.CharField(choices=[('percent', 'percent'), ('real', 'real')], default='real', max_length=10)),
                ('discount_code', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('max_uses', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('uses_count', models.IntegerField(blank=True, null=True)),
                ('is_all', models.BooleanField(default=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('is_all_project', models.BooleanField(default=False)),
                ('is_all_badge', models.BooleanField(default=False)),
                ('is_all_supervisorrequests', models.BooleanField(default=False)),
                ('is_all_workshoprequest', models.BooleanField(default=False)),
                ('is_all_workshop', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CentralRequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('is_do', models.BooleanField(default=0)),
                ('is_do_time', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('destination_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='accounting.agency')),
                ('origin_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='accounting.agency')),
            ],
        ),
    ]
