# Generated by Django 3.2.4 on 2022-07-15 19:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivc_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='blog_images', verbose_name='Image')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish'), ('i', 'Investigation'), ('b', 'Back')], max_length=1, null=True)),
                ('is_top', models.BooleanField(default=False)),
                ('suggest_time', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivc_website.newsmanager')),
                ('category', models.ManyToManyField(related_name='post', to='blog.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
