# Generated by Django 3.2.4 on 2022-06-28 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='')),
                ('status', models.BooleanField(default=True, verbose_name='To be displayed?')),
                ('workshop_and_research', models.BooleanField(default=False, verbose_name='Work shop adn research?')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('status', models.BooleanField(default=True, verbose_name='To be displayed?')),
            ],
        ),
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(default=0, null=True)),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Upload img')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='forum.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TopicComment',
            fields=[
                ('description', models.TextField()),
                ('like', models.IntegerField(default=0, null=True)),
                ('disslike', models.IntegerField(default=0, null=True)),
                ('id_comments', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_t', to='forum.postes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_comment', models.TextField()),
                ('like', models.IntegerField(default=0, null=True)),
                ('disslike', models.IntegerField(default=0, null=True)),
                ('comment_int', models.IntegerField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_t', to='forum.postes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('date_add_to_history', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_history', to='forum.postes')),
            ],
        ),
        migrations.CreateModel(
            name='ForumRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_category_subcategory', models.BooleanField(default=False, null=True, verbose_name='Create category, sub category')),
                ('delete_category_subcategory', models.BooleanField(default=False, null=True, verbose_name='Delete category, sub category')),
                ('edit_category_subcategory', models.BooleanField(default=False, null=True, verbose_name='Edit category, sub category')),
                ('delete_topic', models.BooleanField(default=False, null=True, verbose_name='Delete topic')),
                ('delete_comment_replycomment', models.BooleanField(default=False, null=True, verbose_name='Delete comment, reply comment')),
                ('is_staff', models.BooleanField(default=False, null=True, verbose_name='Is staff')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='forum.maincategory'),
        ),
    ]
