# Generated by Django 3.2.4 on 2022-06-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postes',
            name='like',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='disslike',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='disslike',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='like',
        ),
    ]
