# Generated by Django 3.2.4 on 2022-06-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_dislike_like_viewtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='viewtopic',
            name='status',
        ),
        migrations.AlterField(
            model_name='dislike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_comment', to='forum.topiccomment'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='replycomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_replycomment', to='forum.replycomment'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='status',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='forum.topiccomment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='replycomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_replycomment', to='forum.replycomment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='status',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=50, null=True),
        ),
    ]
