# Generated by Django 3.2.4 on 2022-07-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20220630_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postes',
            name='img',
        ),
    ]
