# Generated by Django 3.2.4 on 2022-07-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20220703_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='postes',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
