# Generated by Django 3.2.4 on 2021-10-23 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivc_website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_profile.jpg', upload_to='members/images', verbose_name='Image')),
                ('position', models.CharField(choices=[('Learner', 'Learner'), ('Member', 'Member'), ('Mentor', 'Mentor'), ('Supervisor', 'Supervisor')], default='Member', max_length=30, verbose_name='Position')),
                ('is_guest', models.BooleanField(default=True)),
                ('is_technical_manager', models.BooleanField(default=False)),
                ('is_research_director', models.BooleanField(default=False)),
                ('field_of_study', models.CharField(choices=[('Biomedical Engineering', 'Biomedical Engineering'), ('Biotechnology', 'Biotechnology'), ('Business', 'Business'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Data Science', 'Data Science'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Environmental Engineering', 'Environmental Engineering'), ('Industrial Engineering', 'Industrial Engineering'), ('Material Science', 'Material Science'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Medical Informatics', 'Medical Informatics'), ('Medical Physics', 'Medical Physics'), ('Medicine', 'Medicine'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Nuclear Medicine Physician', 'Nuclear Medicine Physician'), ('Nuclear physics', 'Nuclear physics'), ('Physics', 'Physics'), ('Statistics', 'Statistics'), ('Medical Engineering', 'Medical Engineering'), ('Other', 'Other')], max_length=150, verbose_name='Field Of Study')),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Employee', 'Employee'), ('Company Manager', 'Company Manager'), ('Post-Doctoral', 'Post-Doctoral'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Status')),
                ('degree', models.CharField(choices=[('Diploma', 'Diploma'), ("Bachelor's degree", "Bachelor's degree"), ("Master's degree", "Master's degree"), ('Doctoral degree', 'Doctoral degree')], default="Bachelor's degree", max_length=50, verbose_name='Degree')),
                ('interest', multiselectfield.db.fields.MultiSelectField(choices=[('Machine Learning', 'Machine Learning'), ('Programming', 'Programming'), ('Statistics', 'Statistics'), ('Mathematics', 'Mathematics')], max_length=51, null=True, verbose_name='Interest')),
                ('about_me', models.TextField(null=True, verbose_name='About Me')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True, verbose_name='Gender')),
                ('time_can_spend_per_day', models.PositiveIntegerField(help_text='Unit is hour', null=True, verbose_name='Time Can Spend Per Day')),
                ('phone', models.CharField(max_length=17, null=True, verbose_name='Phone')),
                ('phone_region', models.CharField(default='IR', max_length=5)),
                ('university', models.CharField(help_text="This is the university you graduated or you're studying now", max_length=100, null=True, verbose_name='University')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('cv_file', models.FileField(default='default.pdf', upload_to='applicants/pdf', verbose_name='CV file')),
                ('skype', models.CharField(blank=True, help_text='Your skype ID', max_length=200, null=True)),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('special_member_access', models.BooleanField(default=False)),
                ('referred_by', models.CharField(blank=True, choices=[('Friends', 'Friends'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Telegram', 'Telegram'), ('Linkedin', 'Linkedin'), ('Search Engine', 'Search Engine')], max_length=200, null=True, verbose_name='Referred by')),
                ('balance', models.IntegerField(default=0)),
                ('is_internship', models.BooleanField(default=False, verbose_name='Internship')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_position', models.CharField(default='Not Determined', max_length=70)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.memberprofile')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ResearchExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('work_area', models.CharField(max_length=200, null=True, verbose_name='Work Area')),
                ('about_company', models.TextField(null=True, verbose_name='About Company')),
                ('phone', models.CharField(max_length=17, null=True, verbose_name='Phone')),
                ('phone_region', models.CharField(default='IR', max_length=5)),
                ('fax', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fax')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('street', models.CharField(max_length=100, null=True, verbose_name='Street')),
                ('zip_code', models.CharField(max_length=50, null=True, verbose_name='Zip Code')),
                ('registration_number', models.CharField(max_length=50, null=True, verbose_name='Registration Number')),
                ('image', models.ImageField(blank=True, default='default_legal.png', null=True, upload_to='members/images', verbose_name='Image')),
                ('skype', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skype')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('contact_preference', models.CharField(blank=True, choices=[('Email Address', 'Email Address'), ('Phone Number', 'Phone Number'), ('Skype', 'Skype')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.BooleanField(null=True)),
                ('disagree', models.BooleanField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivc_website.industrialarea')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.expert')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('initial_password', models.CharField(max_length=10)),
                ('has_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
