# Generated by Django 3.2.4 on 2022-03-07 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeInterviewReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interviewer', 'interviewer'), ('reviewer', 'reviewer')], max_length=50)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('score_file', models.FileField(default='', null=True, upload_to='requets/badge/')),
                ('accept_reject', models.CharField(choices=[('new', 'new'), ('approve', 'approve'), ('decline', 'decline')], default='new', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_degree', models.FileField(default='', null=True, upload_to='request/supervisor/latest_degree/', verbose_name='Latest academic degree')),
                ('valid_evidence', models.FileField(default='', null=True, upload_to='request/supervisor/valid_evidence/', verbose_name='Valid evidence')),
                ('identification', models.FileField(default='', null=True, upload_to='request/supervisor/identification/', verbose_name='Identification')),
                ('latest_resume', models.FileField(default='', null=True, upload_to='request/supervisor/latest_resume/', verbose_name='Latest resume')),
                ('state_of_purpose', models.TextField(blank=True, default='', null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('recommendation_letter', models.FileField(default='', null=True, upload_to='request/supervisor/recommendation_letter/', verbose_name='Recommendation letter')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Review', 'Review'), ('reviewer_evaluated', 'evaluated Reviewer'), ('reviewer_reject', 'Reject Reviewer '), ('send_to_manager', 'Send to manager'), ('accepted_by_manager', 'Accepted by manager'), ('rejected_by_manager', 'Rejected by manager')], default='New', max_length=100)),
                ('score', models.IntegerField(default=0, null=True)),
                ('access_accept_reject', models.BooleanField(default=False, null=True)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_supervisor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_degree', models.FileField(default='', null=True, upload_to='request/workshop/latest_degree/', verbose_name='Latest academic degree')),
                ('valid_evidence', models.FileField(default='', null=True, upload_to='request/workshop/valid_evidence/', verbose_name='Valid evidence')),
                ('identification', models.FileField(default='', null=True, upload_to='request/workshop/identification/', verbose_name='Identification')),
                ('latest_resume', models.FileField(default='', null=True, upload_to='request/workshop/latest_resume/', verbose_name='Latest resume')),
                ('state_of_purpose', models.TextField(blank=True, default='', null=True)),
                ('recommendation_letter', models.FileField(default='', null=True, upload_to='request/workshop/recommendation_letter/', verbose_name='Recommendation letter')),
                ('certificate', models.FileField(default='', null=True, upload_to='request/workshop/certificate/', verbose_name='Certificate')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Review', 'Review'), ('reviewer_evaluated', 'evaluated Reviewer'), ('reviewer_reject', 'Reject Reviewer '), ('send_to_manager', 'Send to manager'), ('accepted_by_manager', 'Accepted by manager'), ('rejected_by_manager', 'Rejected by manager')], default='New', max_length=100)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_workshop', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('score_file', models.FileField(default='', null=True, upload_to='requets/badge/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reject', 'Reject'), ('accept', 'Accept'), ('evaluated', 'Evaluated'), ('not_see', 'Not see'), ('breach_of_promis', 'Breach or promis')], default='new', max_length=20, null=True)),
                ('deadlien', models.DateTimeField(default=datetime.datetime(2022, 3, 7, 13, 58, 59, 321077, tzinfo=utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_request', to='request.workshoprequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('score_file', models.FileField(default='', null=True, upload_to='requets/badge/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reject', 'Reject'), ('accept', 'Accept'), ('evaluated', 'Evaluated'), ('not_see', 'Not see'), ('breach_of_promis', 'Breach or promis')], default='new', max_length=20, null=True)),
                ('deadlien', models.DateTimeField(default=datetime.datetime(2022, 3, 7, 13, 58, 59, 317079, tzinfo=utc), null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_request', to='request.supervisorrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('meeting_link', models.CharField(default='', max_length=200, null=True)),
                ('start_at', models.DateTimeField(null=True)),
                ('time_zone', models.CharField(default='', max_length=400)),
                ('finished', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.badgeinterviewreview')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=30)),
                ('skills', models.CharField(default='', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Review', 'Review'), ('Set-session', 'Set-session'), ('Approve-decline', 'Approve-decline'), ('Interview', 'Interview'), ('Expert-view', 'Expert-view'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='New', max_length=100)),
                ('score', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_request', to='request.badgerequest'),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BadgeExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_expert', to='request.badgerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
