# Generated by Django 3.2.4 on 2022-03-21 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20220321_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Review', 'Review'), ('Set-session', 'Set-session'), ('Approve-decline', 'Approve-decline'), ('Interview', 'Interview'), ('Expert-view', 'Expert-view'), ('send_manager', 'Send to manager'), ('decline-review-interview', 'Decline review, interview'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 9, 25, 4, 385114, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 9, 25, 4, 390109, tzinfo=utc), null=True),
        ),
    ]
