# Generated by Django 3.2.4 on 2022-03-26 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20220321_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='score_9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 12, 13, 44, 885445, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 12, 13, 44, 891441, tzinfo=utc), null=True),
        ),
    ]
