# Generated by Django 3.2.4 on 2022-03-26 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20220326_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeexpert',
            name='access_accept_reject',
        ),
        migrations.AddField(
            model_name='badgerequest',
            name='access_accept_reject',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 19, 24, 48, 814683, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 19, 24, 48, 819680, tzinfo=utc), null=True),
        ),
    ]
