# Generated by Django 3.2.4 on 2022-03-27 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_auto_20220327_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Review', 'Review'), ('reviewer_evaluated', 'evaluated Reviewer'), ('reviewer_accept', 'Accept Reviewer '), ('reviewer_reject', 'Reject Reviewer '), ('send_to_manager', 'Send to manager'), ('accepted_by_manager', 'Accepted by manager'), ('rejected_by_manager', 'Rejected by manager')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 11, 47, 51, 303309, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 11, 47, 51, 307305, tzinfo=utc), null=True),
        ),
    ]
