# Generated by Django 3.2.4 on 2022-03-31 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_auto_20220330_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequest',
            name='reason_reject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 0, 30, 46, 621630, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 0, 30, 46, 621630, tzinfo=utc), null=True),
        ),
    ]
