# Generated by Django 3.2.4 on 2022-03-31 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20220330_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinterviewreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 1, 38, 19, 751760, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 1, 38, 19, 767385, tzinfo=utc), null=True),
        ),
    ]
