# Generated by Django 3.2.4 on 2022-03-31 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_auto_20220330_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinterviewreview',
            name='accept_reject',
            field=models.CharField(choices=[('new', 'new'), ('approve', 'approve'), ('decline', 'decline'), ('not_see', 'not see'), ('breach_of_promis', 'breach of promis')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 1, 52, 2, 953051, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 1, 52, 2, 953051, tzinfo=utc), null=True),
        ),
    ]
