# Generated by Django 3.2.4 on 2022-04-08 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_auto_20220330_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequest',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supervisorrequest',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='badgeinterviewreview',
            name='score_file',
            field=models.FileField(blank='True', default='', null=True, upload_to='requets/badge/'),
        ),
        migrations.AlterField(
            model_name='badgerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Reject-badge-manager', 'Reject-badge-manager'), ('Reject-badge-expert', 'Reject-badge-expert'), ('Review', 'Review'), ('Set-session', 'Set-session'), ('Approve-decline', 'Approve-decline'), ('Interview', 'Interview'), ('Expert-view', 'Expert-view'), ('send_manager', 'Send to manager'), ('decline-review-interview', 'Decline review, interview'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('revise_by_manager', 'Revise by manager')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorrequest',
            name='state_of_purpose',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 8, 3, 46, 820540, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 8, 3, 46, 825537, tzinfo=utc), null=True),
        ),
    ]
