# Generated by Django 3.2.4 on 2022-04-10 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20220408_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequest',
            name='rejected_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='badgerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Reject-badge-manager', 'Reject-badge-manager'), ('Reject-badge-expert', 'Reject-badge-expert'), ('Review', 'Review'), ('Set-session', 'Set-session'), ('Approve-decline', 'Approve-decline'), ('Interview', 'Interview'), ('Expert-view', 'Expert-view'), ('send_manager', 'Send to manager'), ('decline-review-interview', 'Decline review, interview'), ('Accept', 'Accept'), ('Accept-manager', 'Accept-manager'), ('Reject', 'Reject'), ('revise_by_manager', 'Revise by manager')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 12, 3, 4, 725473, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 12, 3, 4, 729470, tzinfo=utc), null=True),
        ),
    ]
