# Generated by Django 3.2.4 on 2022-04-10 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_auto_20220410_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Review', 'Review'), ('reviewer_evaluated', 'evaluated Reviewer'), ('reviewer_accept', 'Accept Reviewer '), ('reviewer_reject', 'Reject Reviewer '), ('send_to_manager', 'Send to manager'), ('accepted_by_manager', 'Accepted by manager'), ('accepted_by_expert', 'Accepted by manager'), ('rejected_by_manager', 'Rejected by manager'), ('rejected_by_expert', 'Rejected by manager')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 14, 25, 16, 456425, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 14, 25, 16, 464422, tzinfo=utc), null=True),
        ),
    ]
