# Generated by Django 3.2.4 on 2022-04-10 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_auto_20220410_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorrequest',
            name='score',
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 14, 47, 46, 642037, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 14, 47, 46, 647030, tzinfo=utc), null=True),
        ),
    ]
