# Generated by Django 3.2.4 on 2022-04-13 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_auto_20220412_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 4, 17, 39, 433625, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Review', 'Review'), ('reviewer_evaluated', 'evaluated Reviewer'), ('reviewer_reject', 'Reject Reviewer '), ('reviewer_accept', 'Accept Reviewer '), ('send_to_manager', 'Send to manager'), ('accepted_by_manager', 'Accepted by manager'), ('accepted_by_expert', 'Accepted by Expert'), ('rejected_by_manager', 'Rejected by manager'), ('rejected_by_expert', 'Rejected by Expert'), ('revised_by_manager', 'Revised by manager'), ('revised_by_expert', 'Revised by Expert')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 4, 17, 39, 438621, tzinfo=utc), null=True),
        ),
    ]
