# Generated by Django 3.2.4 on 2022-04-13 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0026_auto_20220412_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 4, 19, 38, 981497, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 4, 19, 38, 986492, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reject', 'Reject'), ('accept', 'Accept'), ('evaluated', 'Evaluated'), ('revise', 'Revise'), ('done', 'Done'), ('not_see', 'Not see'), ('breach_of_promis', 'Breach or promis')], default='new', max_length=20, null=True),
        ),
    ]
