# Generated by Django 3.2.4 on 2022-04-17 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_auto_20220412_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequest',
            name='revised_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supervisorrequest',
            name='revised_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supervisorreview',
            name='declined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workshoprequest',
            name='revised_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workshopreview',
            name='declined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supervisorreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 12, 32, 57, 898747, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='deadlien',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 12, 32, 57, 904744, tzinfo=utc), null=True),
        ),
    ]
