# Generated by Django 3.2.4 on 2022-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsinstitute',
            name='tags',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
