# Generated by Django 3.2.4 on 2022-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_auto_20220719_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='tags',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='emailsinstitute',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True, verbose_name='Gender'),
        ),
    ]
