# Generated by Django 3.2.4 on 2022-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_auto_20220721_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='emailsinstitute',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True, verbose_name='Gender'),
        ),
    ]
