# Generated by Django 3.2.4 on 2022-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0006_auto_20220721_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemailproject',
            name='projectlink',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sendemailproject',
            name='tilte',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='emailsinstitute',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
    ]
