# Generated by Django 3.2.4 on 2021-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivc_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_equipments',
        ),
        migrations.AddField(
            model_name='project',
            name='project_equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Project Equipment'),
        ),
    ]
